### ISSUE TITLE
whitespace issues (see ticket)

### ISSUE THREAD

**Issue by busstram** [wingscms/wings#184]

**Comment by jaapstronks** [comment]
@markjjackson https://fnv-picnic.netlify.com still has the issue of too much white space below the title. You may still be working on implementing HB improvements to other websites, but in that case, perhaps these cards should not be marked as complete / archived, because tracking progress of these improvements is often primarily necessary because specific client projects require this improvement. Or should we track these client-specific implementations on Trello?
